package toadmess.explosives.events;

public enum TippingPoint {
	CAN_CHANGE_CREATURE_DAMAGE,
	CAN_CHANGE_ITEM_DAMAGE,	
	CAN_CHANGE_PLAYER_DAMAGE,
	
	CAN_PREVENT_TERRAIN_DAMAGE,
	
	CAN_CHANGE_EXPLOSION_FIRE_FLAG,
	CAN_CHANGE_EXPLOSION_RADIUS,
	CAN_CHANGE_EXPLOSION_YIELD,
	
	TNT_PRIMED_BY_FIRE,
	TNT_PRIMED_BY_PLAYER,
	TNT_PRIMED_BY_REDSTONE, 
	
	AN_EXPLOSION,
	AN_EXPLOSION_CANCELLED,
}
