name: HigherExplosives
author: toadmess
description: Per world control over size, yield and player/creature/terrain/item damage of explosions and TNT fuse durations.
version: 1.7
main: toadmess.explosives.HEMain
